// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgv-Zv09md7pau6WpVron89YlNZlGKg_c',
    appId: '1:344005987112:web:d6bcbec9d2e3e0981dde1d',
    messagingSenderId: '344005987112',
    projectId: 'firbaseloginkimo',
    authDomain: 'firbaseloginkimo.firebaseapp.com',
    storageBucket: 'firbaseloginkimo.appspot.com',
    measurementId: 'G-D3XEMN8HRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBu1es73jWmjvinY_2flwLCqeEwcL_uvE',
    appId: '1:344005987112:android:6a8d00cfd8678fb71dde1d',
    messagingSenderId: '344005987112',
    projectId: 'firbaseloginkimo',
    storageBucket: 'firbaseloginkimo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ArAF5rNezGvZYc0gyxOtbuYtemUQGuc',
    appId: '1:344005987112:ios:694ebe33448849641dde1d',
    messagingSenderId: '344005987112',
    projectId: 'firbaseloginkimo',
    storageBucket: 'firbaseloginkimo.appspot.com',
    iosClientId: '344005987112-ji3b7qpshnoq81j6a82qb3k5lne8s0ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseSignupSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ArAF5rNezGvZYc0gyxOtbuYtemUQGuc',
    appId: '1:344005987112:ios:694ebe33448849641dde1d',
    messagingSenderId: '344005987112',
    projectId: 'firbaseloginkimo',
    storageBucket: 'firbaseloginkimo.appspot.com',
    iosClientId: '344005987112-ji3b7qpshnoq81j6a82qb3k5lne8s0ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseSignupSignin',
  );
}
